version: "3.7"
services:
  backend:
    container_name: nodebackend
    restart: always
    image: nodebackend:mcc
    build: .
    ports: 
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.2.0
    ports:
      - '1048:27017'